### ISSUE TITLE
Fungible tokens, deposit/withdraw correlation and account linking

### ISSUE THREAD

**Issue by HarryR** [EYBlockchain/ZKPChallenge#3]
While I haven't been able to look at the source code for this project, but from reading the description there are a few issues which have been facing us all for the past few years, which your project suffers from too:

 1. Deposit / Withdraw correlation with fungible tokens.

 2. Account linking via gas payer

The two combined are the death knell for any project which claims to offer anonymity on Ethereum, and it seems you have no novel solutions here. The solution is account abstraction - which could make multiple actions by the same party unlinkable (such as Deposit and Withdraw).

The first problem (deposit/withdraw correlation) is also faced by UXTO mixers, where over a span of time an amount of value is deposited to a single address then the exact same value is deposited into multiple other accounts. This creates a correlatory linking between the input and output which signifies they are the same entity - with a relatively small margin for error. With any fungible token that can be deposited into an 'anonymous enclave' - it's only anonymous while it stays there. Having to work around these hurdles results in a very brittle security guarantee where any user may inadvertently destroy their own privacy assumptions by simply using the system how it should've been usable - ZCash suffers from this problem because 95%+ of the transactions are 'transparent' while Monero doesn't... Your proposed system has even more problems than ZCash and is far from anonymous in this regard.

The second problem is that, even if I can't correlate/link transactions by the input and output amounts - as you would do to trace UXTO mixers - I can see every transaction you make by linking the gas payers together. While it may not be able to link inputs from other people to your outputs it can reveal your actions - and the correlation between person A depositing and person B withdrawing reveals even more information.

**Comment by Westlad** [comment]
Thanks for your thoughts.  Yes We're familiar with these sort of attacks on a utxo tumbler.  The first type of analysis has been used successfully on zcash but it really only succeeds because the network is used naively. By careful use of commitment transformations I think you can hide transactions well. Gas tracing is a harder problem, ultimately we need to have a way to trigger commitment transformations from a one-use account without needing gas. For the moment, the best approaches are separate coinbase accounts that are mined into and used to fund the gas. 
I'd also suggest that the approach we've used for non fungibles is more robust to tracing because there is never a need to reveal the commitment on the blockchain. You only ever put a hash of a swarm-hash on the blockchain, never the actual hash.
I'll let others decide how novel that approach is but our aim is to find ways to get organisations trading value on the Ethereum blockchain and hopefully that will be good for everyone.
